site_name: My Alias - Docs

repo_url: https://github.com/thiagomeloo/myalias
repo_name: My Alias
edit_uri: tree/main/docs
copyright: Created by Thiago Melo 


theme:
  name: material
  # logo: assets/img/logo.png
  # favicon: assets/img/logo.png
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.sections
    - navigation.expand
    - navigation.instant
    - navigation.footer
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      primary: light green
      accent: light green
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      primary: light green
      accent: light green
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: light green
      accent: light green
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

extra:
  social:
    - icon: fontawesome/brands/github
      link: github.com/thiagomeloo/myalias


markdown_extensions:
  - attr_list

extra_css:
  - assets/css/custom.css

plugins:
- mkdocstrings:
    handlers:
      python:
        paths: [myalias]
